# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='document.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x64ocument.proto\"\x9d\x01\n\x0f\x44ocumentMessage\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\x10\n\x08\x64oc_name\x18\x02 \x01(\t\x12\x34\n\x12\x65ntity_link_totals\x18\x03 \x03(\x0b\x32\x18.EntityLinkTotalsMessage\x12\x32\n\x11\x64ocument_contents\x18\x04 \x03(\x0b\x32\x17.DocumentContentMessage\"\xdb\x01\n\x17\x45ntityLinkTotalsMessage\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_name\x18\x02 \x01(\t\x12R\n\x15\x61nchor_text_frequency\x18\x03 \x03(\x0b\x32\x33.EntityLinkTotalsMessage.AnchorTextFrequencyMessage\x1a\x44\n\x1a\x41nchorTextFrequencyMessage\x12\x13\n\x0b\x61nchor_text\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\x05\"\x90\x03\n\x16\x44ocumentContentMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x12section_heading_id\x18\x02 \x01(\t\x12\x1c\n\x14section_heading_name\x18\x03 \x01(\t\x12\"\n\x1aparent_section_heading_ids\x18\x04 \x03(\t\x12$\n\x1cparent_section_heading_names\x18\x05 \x03(\t\x12\x41\n\x0cobjects_type\x18\x06 \x01(\x0e\x32+.DocumentContentMessage.DocumentContentType\x12\x0c\n\x04text\x18\x07 \x01(\t\x12!\n\x0c\x65ntity_links\x18\x08 \x03(\x0b\x32\x0b.EntityLink\x12\x14\n\x0c\x63ontent_urls\x18\t \x03(\t\"\\\n\x13\x44ocumentContentType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tPARAGRAPH\x10\x01\x12\t\n\x05IMAGE\x10\x02\x12\x08\n\x04LIST\x10\x03\x12\t\n\x05VIDEO\x10\x04\x12\t\n\x05\x41UDIO\x10\x05\"\xc7\x01\n\nEntityLink\x12\x13\n\x0b\x61nchor_text\x18\x01 \x01(\t\x12\x43\n\x14\x61nchor_text_location\x18\x02 \x01(\x0b\x32%.EntityLink.AnchorTextLocationMessage\x12\x11\n\tentity_id\x18\x03 \x01(\t\x12\x13\n\x0b\x65ntity_name\x18\x04 \x01(\t\x1a\x37\n\x19\x41nchorTextLocationMessage\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x62\x06proto3'
)



_DOCUMENTCONTENTMESSAGE_DOCUMENTCONTENTTYPE = _descriptor.EnumDescriptor(
  name='DocumentContentType',
  full_name='DocumentContentMessage.DocumentContentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARAGRAPH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMAGE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIST', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUDIO', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=709,
  serialized_end=801,
)
_sym_db.RegisterEnumDescriptor(_DOCUMENTCONTENTMESSAGE_DOCUMENTCONTENTTYPE)


_DOCUMENTMESSAGE = _descriptor.Descriptor(
  name='DocumentMessage',
  full_name='DocumentMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doc_id', full_name='DocumentMessage.doc_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doc_name', full_name='DocumentMessage.doc_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_link_totals', full_name='DocumentMessage.entity_link_totals', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='document_contents', full_name='DocumentMessage.document_contents', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=176,
)


_ENTITYLINKTOTALSMESSAGE_ANCHORTEXTFREQUENCYMESSAGE = _descriptor.Descriptor(
  name='AnchorTextFrequencyMessage',
  full_name='EntityLinkTotalsMessage.AnchorTextFrequencyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anchor_text', full_name='EntityLinkTotalsMessage.AnchorTextFrequencyMessage.anchor_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='EntityLinkTotalsMessage.AnchorTextFrequencyMessage.frequency', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=398,
)

_ENTITYLINKTOTALSMESSAGE = _descriptor.Descriptor(
  name='EntityLinkTotalsMessage',
  full_name='EntityLinkTotalsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='EntityLinkTotalsMessage.entity_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_name', full_name='EntityLinkTotalsMessage.entity_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anchor_text_frequency', full_name='EntityLinkTotalsMessage.anchor_text_frequency', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENTITYLINKTOTALSMESSAGE_ANCHORTEXTFREQUENCYMESSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=398,
)


_DOCUMENTCONTENTMESSAGE = _descriptor.Descriptor(
  name='DocumentContentMessage',
  full_name='DocumentContentMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DocumentContentMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='section_heading_id', full_name='DocumentContentMessage.section_heading_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='section_heading_name', full_name='DocumentContentMessage.section_heading_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_section_heading_ids', full_name='DocumentContentMessage.parent_section_heading_ids', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_section_heading_names', full_name='DocumentContentMessage.parent_section_heading_names', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects_type', full_name='DocumentContentMessage.objects_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='DocumentContentMessage.text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_links', full_name='DocumentContentMessage.entity_links', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_urls', full_name='DocumentContentMessage.content_urls', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DOCUMENTCONTENTMESSAGE_DOCUMENTCONTENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=801,
)


_ENTITYLINK_ANCHORTEXTLOCATIONMESSAGE = _descriptor.Descriptor(
  name='AnchorTextLocationMessage',
  full_name='EntityLink.AnchorTextLocationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='EntityLink.AnchorTextLocationMessage.start', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='EntityLink.AnchorTextLocationMessage.end', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=948,
  serialized_end=1003,
)

_ENTITYLINK = _descriptor.Descriptor(
  name='EntityLink',
  full_name='EntityLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anchor_text', full_name='EntityLink.anchor_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anchor_text_location', full_name='EntityLink.anchor_text_location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='EntityLink.entity_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_name', full_name='EntityLink.entity_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENTITYLINK_ANCHORTEXTLOCATIONMESSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=804,
  serialized_end=1003,
)

_DOCUMENTMESSAGE.fields_by_name['entity_link_totals'].message_type = _ENTITYLINKTOTALSMESSAGE
_DOCUMENTMESSAGE.fields_by_name['document_contents'].message_type = _DOCUMENTCONTENTMESSAGE
_ENTITYLINKTOTALSMESSAGE_ANCHORTEXTFREQUENCYMESSAGE.containing_type = _ENTITYLINKTOTALSMESSAGE
_ENTITYLINKTOTALSMESSAGE.fields_by_name['anchor_text_frequency'].message_type = _ENTITYLINKTOTALSMESSAGE_ANCHORTEXTFREQUENCYMESSAGE
_DOCUMENTCONTENTMESSAGE.fields_by_name['objects_type'].enum_type = _DOCUMENTCONTENTMESSAGE_DOCUMENTCONTENTTYPE
_DOCUMENTCONTENTMESSAGE.fields_by_name['entity_links'].message_type = _ENTITYLINK
_DOCUMENTCONTENTMESSAGE_DOCUMENTCONTENTTYPE.containing_type = _DOCUMENTCONTENTMESSAGE
_ENTITYLINK_ANCHORTEXTLOCATIONMESSAGE.containing_type = _ENTITYLINK
_ENTITYLINK.fields_by_name['anchor_text_location'].message_type = _ENTITYLINK_ANCHORTEXTLOCATIONMESSAGE
DESCRIPTOR.message_types_by_name['DocumentMessage'] = _DOCUMENTMESSAGE
DESCRIPTOR.message_types_by_name['EntityLinkTotalsMessage'] = _ENTITYLINKTOTALSMESSAGE
DESCRIPTOR.message_types_by_name['DocumentContentMessage'] = _DOCUMENTCONTENTMESSAGE
DESCRIPTOR.message_types_by_name['EntityLink'] = _ENTITYLINK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DocumentMessage = _reflection.GeneratedProtocolMessageType('DocumentMessage', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTMESSAGE,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:DocumentMessage)
  })
_sym_db.RegisterMessage(DocumentMessage)

EntityLinkTotalsMessage = _reflection.GeneratedProtocolMessageType('EntityLinkTotalsMessage', (_message.Message,), {

  'AnchorTextFrequencyMessage' : _reflection.GeneratedProtocolMessageType('AnchorTextFrequencyMessage', (_message.Message,), {
    'DESCRIPTOR' : _ENTITYLINKTOTALSMESSAGE_ANCHORTEXTFREQUENCYMESSAGE,
    '__module__' : 'document_pb2'
    # @@protoc_insertion_point(class_scope:EntityLinkTotalsMessage.AnchorTextFrequencyMessage)
    })
  ,
  'DESCRIPTOR' : _ENTITYLINKTOTALSMESSAGE,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:EntityLinkTotalsMessage)
  })
_sym_db.RegisterMessage(EntityLinkTotalsMessage)
_sym_db.RegisterMessage(EntityLinkTotalsMessage.AnchorTextFrequencyMessage)

DocumentContentMessage = _reflection.GeneratedProtocolMessageType('DocumentContentMessage', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTCONTENTMESSAGE,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:DocumentContentMessage)
  })
_sym_db.RegisterMessage(DocumentContentMessage)

EntityLink = _reflection.GeneratedProtocolMessageType('EntityLink', (_message.Message,), {

  'AnchorTextLocationMessage' : _reflection.GeneratedProtocolMessageType('AnchorTextLocationMessage', (_message.Message,), {
    'DESCRIPTOR' : _ENTITYLINK_ANCHORTEXTLOCATIONMESSAGE,
    '__module__' : 'document_pb2'
    # @@protoc_insertion_point(class_scope:EntityLink.AnchorTextLocationMessage)
    })
  ,
  'DESCRIPTOR' : _ENTITYLINK,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:EntityLink)
  })
_sym_db.RegisterMessage(EntityLink)
_sym_db.RegisterMessage(EntityLink.AnchorTextLocationMessage)


# @@protoc_insertion_point(module_scope)
