# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\npage.proto\"\xa7\x01\n\x0bPageMessage\x12\x0b\n\x03idx\x18\x01 \x01(\x03\x12\r\n\x05\x63hunk\x18\x02 \x01(\x03\x12\x0f\n\x07page_id\x18\x03 \x01(\t\x12\x11\n\tpage_name\x18\x04 \x01(\t\x12\x16\n\x0epage_bytearray\x18\x05 \x01(\x0c\x12@\n\x18synthetic_entity_linking\x18\x06 \x01(\x0b\x32\x1e.SyntheticEntityLinkingMessage\"E\n\x1dSyntheticEntityLinkingMessage\x12\x10\n\x08skeleton\x18\x01 \x01(\x0c\x12\x12\n\nparagraphs\x18\x02 \x01(\x0c\x62\x06proto3'
)




_PAGEMESSAGE = _descriptor.Descriptor(
  name='PageMessage',
  full_name='PageMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='PageMessage.idx', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk', full_name='PageMessage.chunk', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_id', full_name='PageMessage.page_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_name', full_name='PageMessage.page_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_bytearray', full_name='PageMessage.page_bytearray', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='synthetic_entity_linking', full_name='PageMessage.synthetic_entity_linking', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=182,
)


_SYNTHETICENTITYLINKINGMESSAGE = _descriptor.Descriptor(
  name='SyntheticEntityLinkingMessage',
  full_name='SyntheticEntityLinkingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skeleton', full_name='SyntheticEntityLinkingMessage.skeleton', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paragraphs', full_name='SyntheticEntityLinkingMessage.paragraphs', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=253,
)

_PAGEMESSAGE.fields_by_name['synthetic_entity_linking'].message_type = _SYNTHETICENTITYLINKINGMESSAGE
DESCRIPTOR.message_types_by_name['PageMessage'] = _PAGEMESSAGE
DESCRIPTOR.message_types_by_name['SyntheticEntityLinkingMessage'] = _SYNTHETICENTITYLINKINGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PageMessage = _reflection.GeneratedProtocolMessageType('PageMessage', (_message.Message,), {
  'DESCRIPTOR' : _PAGEMESSAGE,
  '__module__' : 'page_pb2'
  # @@protoc_insertion_point(class_scope:PageMessage)
  })
_sym_db.RegisterMessage(PageMessage)

SyntheticEntityLinkingMessage = _reflection.GeneratedProtocolMessageType('SyntheticEntityLinkingMessage', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHETICENTITYLINKINGMESSAGE,
  '__module__' : 'page_pb2'
  # @@protoc_insertion_point(class_scope:SyntheticEntityLinkingMessage)
  })
_sym_db.RegisterMessage(SyntheticEntityLinkingMessage)


# @@protoc_insertion_point(module_scope)
